import { signupPassword } from "./dataPage";

export default {
    shopMenu: '.shop-menu',
    subscriptionLabel: '.single-widget', 
    signupName: '[data-qa="signup-name"]',
    singupEmail: '[data-qa="signup-email"]', 
    signupBtn: '[data-qa="signup-button"]',
    signupGender: '#id_gender2',
    signupPassword: '[data-qa="password"]',
    singupDateOfBirthDay: '[data-qa="days"]',
    singupDateOfBirthMonth: '[data-qa="months"]',
    singupDateOfBirthYear: '[data-qa="years"]',
    signupCheckboxNewsletter: '#newsletter',
    signupcheckboxReceive: '#uniform-optin #optin',
    signupFirstName: '[data-qa="first_name"]',
    singupLastName: '[data-qa="last_name"]',
    singupCompany: '[data-qa="company"]',
    singupAddress: '[data-qa="address"]',
    singupAddress2: '[data-qa="address2"]',
    singupCountry: '[data-qa="country"]',
    singupState: '[data-qa="state"]',
    signupCity: '[data-qa="city"]',
    signupZipcode: '[data-qa="zipcode"]',
    signupMobileNumber: '[data-qa="mobile_number"]',
    signupBtnCreateAccount: '[data-qa="create-account"]',
    signupCreateComment: '[data-qa="account-created"]',
    signupBtnContinue: '[data-qa="continue-button"]',
    loginEmail: '[data-qa="login-email"]',
    loginPassword: '[data-qa="login-password"]',
    loginBtn: '[data-qa="login-button"]',
    inputSearchProducts: '#search_product',
    btnSubmitSearch: '#submit_search',
    searchProductNameTag: '.productinfo p',

    viewProductDetails: `[href="/product_details/1"]`,
    productDetailsAvailability: ':nth-child(6) > b',
    productDetailsAvailabilityValue: '.product-information > :nth-child(6)',
    btnAddProductFromDetailsPage: '.btn.btn-default.cart',
    addFirstProductInTheCart: '[data-product-id="1"]',

    addSecondProductInTheCart: '[data-product-id="2"]',
    addThirdProductInTheCart: '[data-product-id="3"]',
    addFourthProductInTheCart: '[data-product-id="4"]',

    btnContinueShopping: '.btn.btn-success.close-modal.btn-block',
    informCartIsEmpty: '#empty_cart b',
    cartItemsQuantities: 'tbody tr',
    filterTitlePanel: '.panel-title',
    filterBodyPanel: '.panel-body',

    btnCheckout: '.check_out',
    loginFromCart: '.modal-body a',
    nameOnCard: '[data-qa="name-on-card"]',
    cardNumber: '[data-qa="card-number"]',
    cvcData: '[data-qa="cvc"]',
    expirationDate: '[data-qa="expiry-month"]',
    expirationYear: '[data-qa="expiry-year"]',
    btnsubmitOrder: '.submit-button',
    labelOrderPlaced: '[data-qa="order-placed"]',



}